# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd0f934608603c116106ed6dddc1da4144e52d1495a51c532792b75656cf922ff6750550c2ff760e035bdf4fa2d6f13a873d27287e1dac01bff5894677836dfa

test:
  secret_key_base: c97b8df807ec4a6faf3a5f0835f79b64da9f1d0cd0b4d8ab7a87152b4695a749b6574ddcbaf6f52e02cb4ce62cf2f4b6d190160b93cee132a70bd5cba13b13a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
